import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
import joblib
import warnings
warnings.filterwarnings('ignore')

# --- 1. LOAD & SCRUB THE MULTIMODAL DATA ---
print("Loading RELATIVE_MULTIMODAL_DATASET.csv...")
df = pd.read_csv("RELATIVE_MULTIMODAL_DATASET.csv")

# 🛑 CRITICAL MATH FIX: The Forensic Scrubber
# Catching the NaN values generated by the first-frame variance calculation
nan_count = df.isna().sum().sum()
if nan_count > 0:
    print(f"⚠️ Neutralized {nan_count} 'NaN' mathematical errors from the dataset.")

# Replace Inf and NaN with absolute 0
df = df.replace([np.inf, -np.inf], np.nan).fillna(0)

# Clean labels to prevent mapping errors
df['Target_Label'] = df['Target_Label'].astype(str).str.strip()

exclude = ['Session_ID', 'Timestamp', 'Frame', 'Target_Label']
feature_cols = [c for c in df.columns if c in df.columns and c not in exclude]
X_raw = df[feature_cols].values

# Map labels securely
label_mapping = {'NORMAL': 0, 'CHEAT_PHYSICAL': 1, 'CHEAT_DIGITAL': 2}
y_raw = df['Target_Label'].map(label_mapping).values

# Safety Check: If mapping failed due to weird CSV formatting, stop the script
if pd.isna(y_raw).any():
    print("❌ ERROR: Unrecognized labels found in Target_Label column. Check your CSV for typos.")
    exit()

print(f"Features mapped securely ({len(feature_cols)} total).")

# Scale the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_raw)
joblib.dump(scaler, "multimodal_scaler.pkl")

# --- 2. SEQUENCE GENERATION ---
def create_sequences(data, labels, seq_length=60):
    X_seq, y_seq = [], []
    for i in range(len(data) - seq_length):
        X_seq.append(data[i:i+seq_length])
        y_seq.append(labels[i+seq_length-1])
    return np.array(X_seq), np.array(y_seq)

print("Slicing data into 60-frame sequential blocks...")
X_s, y_s = create_sequences(X_scaled, y_raw)
X_train, X_test, y_train, y_test = train_test_split(X_s, y_s, test_size=0.2, stratify=y_s, random_state=42)

train_data = TensorDataset(torch.FloatTensor(X_train), torch.LongTensor(y_train))
test_data = TensorDataset(torch.FloatTensor(X_test), torch.LongTensor(y_test))
train_loader = DataLoader(train_data, batch_size=64, shuffle=True)
test_loader = DataLoader(test_data, batch_size=64)

# --- 3. THE MULTIMODAL 1D-CNN + BiLSTM ---
class MultimodalBehavioralEngine(nn.Module):
    def __init__(self, input_size=len(feature_cols), hidden_size=64, num_layers=2):
        super(MultimodalBehavioralEngine, self).__init__()
        
        self.cnn = nn.Sequential(
            nn.Conv1d(in_channels=input_size, out_channels=32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool1d(kernel_size=2)
        )
        
        self.lstm = nn.LSTM(input_size=32, hidden_size=hidden_size, num_layers=num_layers, 
                            batch_first=True, bidirectional=True, dropout=0.3)
        
        self.fc = nn.Sequential(
            nn.Linear(hidden_size * 2, 64),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(64, 3)
        )
        
    def forward(self, x):
        x = x.permute(0, 2, 1) 
        cnn_out = self.cnn(x)
        cnn_out = cnn_out.permute(0, 2, 1)
        lstm_out, _ = self.lstm(cnn_out)
        return self.fc(lstm_out[:, -1, :])

# --- 4. TRAINING WITH PENALTY WEIGHTS ---
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = MultimodalBehavioralEngine().to(device)

class_weights = compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)
criterion = nn.CrossEntropyLoss(weight=torch.FloatTensor(class_weights).to(device))
optimizer = optim.Adam(model.parameters(), lr=0.0005)

print(f"\n🚀 Starting Multimodal AI Training on {device}...")
for epoch in range(25):
    model.train()
    total_loss = 0
    for batch_x, batch_y in train_loader:
        batch_x, batch_y = batch_x.to(device), batch_y.to(device)
        
        optimizer.zero_grad()
        outputs = model(batch_x)
        loss = criterion(outputs, batch_y)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        total_loss += loss.item()
    
    model.eval()
    correct = 0
    with torch.no_grad():
        for bx, by in test_loader:
            bx, by = bx.to(device), by.to(device)
            preds = model(bx).argmax(1)
            correct += (preds == by).sum().item()
    
    acc = (correct / len(test_data)) * 100
    print(f"Epoch {epoch+1}/25 | Loss: {total_loss/len(train_loader):.4f} | Validation Acc: {acc:.2f}%")

torch.save(model.state_dict(), "multimodal_behavioral_engine.pth")
print("\n✅ Multimodal Engine Saved as 'multimodal_behavioral_engine.pth'")
print("✅ Scaler Saved as 'multimodal_scaler.pkl'")